### ISSUE TITLE
HBase 최신버전에는 적용이 안되나요?

### ISSUE THREAD

**Issue by jaewoosung** [kakao/hbase-region-inspector#4]
HBase 버전 1.2.6으로 사용해보려고 하는데 다음과 같은 오류가 나오네요..
Can't get master address from zooKeeper; znode data == null

분명히 클러스터 구동은 잘 되고 있는 상황입니다.

**Comment by junegunn** [comment]
HBase 1.2 에서도 정상 작동합니다. 전체 에러 메시지를 보여주시겠어요?

ZooKeeper 에 정상적으로 접근되는지 먼저 확인해보시면 좋을 것 같습니다
- `zkCli 주키퍼주소` 접속 후 `ls /hbase`

**Comment by jaewoosung** [comment]
아, 설정상 zookeeper parent node를 hbase-unsecure로 설정해놨었는데 다시 hbase로 바꾸니까 정상 작동합니다 감사합니다

**Comment by junegunn** [comment]
네, 디폴트가 아닌 node 명을 쓰실 때는 현재로선 별도의 설정 파일을 만들어서 이걸 인자로 실행하셔야 합니다.

```properties
hbase.zookeeper.quorum = your.zookeeper.host
zookeeper.znode.parent = /hbase-unsecure
```

아무래도 좀 번거로워서, 나중에는 `./hbase-region-inspector your.zookeeper.host/hbase-unsecure` 같은 형태로 실행할 수 있도록 할까 생각도 하고 있는데요, 개선되면 이 쪽에 커멘트 달아둘께요.

**Comment by jaewoosung** [comment]
빠른 답변 감사드립니다. 툴 아주 좋은 것 같아요! ^^
